baseURL = "https://michael-friska.liondy.com/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Michael & Friska"

[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "10s"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Opinion"
url = "#opinion"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 8



[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "Copyright © Michael-Friska 2021"
footerLogo = "images/site-navigation/logo.png"
formspreeURL = "https://formspree.io/f/meqvrojw"
googleAnalytics = "G-Q2GP6YVC0R"
logo = "images/site-navigation/logo.png"
custom_css = ["css/style.css"]
testiURL = "/testi"
opinionURL = "https://opinion-michael-friska.liondy.com"

[params.address]
address = "Bandung, Indonesia"
email = "mike@liondy.com"
openingHours = "All day"
phone = "+(62) 878 7381 9629"

[params.map]
APIkey = "AIzaSyBZgDQl6W0YVfoPFropC4ZTClBhKBb0PTU"
latitude = "-6.914864"
longitude = "107.608238"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/coded.by.michael"
title = "Mikes Code Facebook Page"
weight = 1
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/friska.christiana1"
title = "Friska Facebook Page"
weight = 2
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/michael-liondy/"
title = "Mike Linkedin"
weight = 3
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/friska-christiana/"
title = "Friska Linkedin"
weight = 4

ignoreErrors = ["error-remote-getjson"]