version: '3'

services:
  hugo:
    container_name: hugo
    # image: peaceiris/hugo:v0.x.x
    # image: peaceiris/hugo:v0.x.x-mod   # Hugo Modules
    image: peaceiris/hugo:v0.85.0-full  # Hugo Modules and Node.js
    ports:
      - 1313:1313
    volumes:
      - ${PWD}:/src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts